pipeline {
    agent any
    triggers {
        pollSCM('*/1 * * * *') // poll the SCM every 1 minutes
    }

    stages {
        stage('Clone repository') {
            steps {
                echo 'Cloning CI_with_Jenkins...'
                deleteDir() // Delete workspace before cloning
                sh 'git clone https://github.com/justinyeh1995/CI_with_Jenkins.git'
            }
        }
        stage('Build cpswt-meta image') {
            steps {
                echo 'Start a Docker Container for this experiment, which should start the experiment and a archiva server, a inet server, and a omnet++ server..'
                sh 'pwd'
                dir("CI_with_Jenkins/cpswt-meta") {
                    sh 'docker build -t cpswt-meta:latest -f Dockerfile --build-arg ssh_prv_key="$(cat ~/.ssh/id_rsa)" --build-arg ssh_pub_key="$(cat ~/.ssh/id_rsa.pub)" .'
                }
            }
        }
        stage('Deploy image') {
            steps {
                echo 'Run the Docker Container inside Jenkins container'
                sh 'docker run \
                        --name cpswt-meta \
                        --publish 8081:8080 \
                        -v /var/run/docker.sock:/var/run/docker.sock \
                        cpswt-meta:latest'
            }
        }
        stage('Wait for cpswt-meta container to stop') {
            options {
                timeout(time: 30, unit: 'MINUTES')
            }
            steps {
                echo 'Wait for container to stop'
                sh 'docker wait cpswt-meta'
            }
        }
        stage('Output HelloWorldJava from container') {
            steps {
                sh 'docker cp cpswt-meta:/tmp/HelloWorldJava.zip .'
                sh 'unzip HelloWorldJava.zip -d .'
            }
        }
        stage('Build HelloWorldJava image') {
            steps {
                echo 'Start a Docker Container for HelloWorldJava'
                sh 'docker build -t helloworldjava:latest -f HelloWorldJava.Dockerfile .'
            }
        }
        stage('Deploy HelloWorldJava image') {
            steps {
                echo 'Run the Docker Container for HelloWorldJava'
                sh 'docker run \
                        --name helloworldjava \
                        --publish 8082:8080 \
                        -v /var/run/docker.sock:/var/run/docker.sock \
                        helloworldjava:latest'
            }
        }
        stage('Wait for HelloWorldJava container to stop') {
            options {
                timeout(time: 30, unit: 'MINUTES')
            }
            steps {
                echo 'Wait for container to stop'
                sh 'docker wait helloworldjava'
            }
        }
        stage('Archive loggings') {
            steps {
                echo 'Archiving cpswt-meta & HelloWorldJava results...'
                sh 'docker logs helloworldjava > helloworldjava.log'
                sh 'docker logs cpswt-meta > cpswt-meta.log'
                archiveArtifacts artifacts: 'cpswt-meta.log', fingerprint: true
                archiveArtifacts artifacts: 'helloworldjava.log', fingerprint: true
            }
        }
        stage('Clean up') {
            steps {
                echo 'Tearing Down the image & container....'
                sh 'docker rm -f cpswt-meta'
                sh 'docker rm -f helloworldjava'
                sh 'docker rmi helloworldjava:latest'
                sh 'docker rmi cpswt-meta:latest'
                sh 'rm -rf cpswt-meta'
                sh 'rm -rf HelloWorldJava.zip HelloWorldJava'
                sh 'rm -rf cpswt-meta.log helloworldjava.log'
            }
        }
    }

    post {
        always {
    	echo 'This will always run'
	    emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
        recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
        subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
	    attachLog: true,
        attachmentsPattern: 'cpswt-core.log'
        }
    }	
}

// pipeline {
//     agent any
//     triggers {
//         pollSCM('*/1 * * * *') // poll the SCM every 1 minute
//     }

//     stages {
//         stage('Clone repository') {
//             steps {
//                 echo 'Cloning Forked CPSWT-Core..'
//                 deleteDir() // Delete workspace before cloning
//                 git url: 'https://github.com/justinyeh1995/cpswt-core.git', branch: 'develop'
//             }
//         }
//         stage('Build image') {
//             steps {
//                 echo 'Start a Docker Container for this experiment, which should start the experiment and an Archiva server, an Inet server, and an OMNeT++ server..'
//                 dir('cpswt-core') {
//                     docker.build('cpswt-core:latest')
//                 }
//             }
//         }
//         stage('Check network') {
//             steps {
//                 echo 'Checking if cpswt-core network is in Docker network....'
//                 script {
//                     def networkExists = sh(script: 'docker network ls | grep cpswt-core', returnStatus: true)
//                     if (networkExists == 0) {
//                         echo "cpswt-core network exists"
//                     } else {
//                         sh 'docker network create cpswt-core'
//                     }
//                 }
//             }
//         }
//         stage('Deploy image') {
//             steps {
//                 echo 'Run the Docker Container....'
//                 script {
//                     docker.image('cpswt-core:latest').withRun('--name cpswt-core \
//                             --restart=on-failure \
//                             --detach \
//                             --network cpswt-core \
//                             --env DOCKER_HOST=tcp://docker:2376 \
//                             --env DOCKER_CERT_PATH=/certs/client \
//                             --env DOCKER_TLS_VERIFY=1 \
//                             --publish 8081:8080 \
//                             -v /var/run/docker.sock:/var/run/docker.sock') {
//                         // Additional setup or commands inside the container if needed
//                     }
//                 }
//             }
//         }
//         stage('Archive loggings') {
//             steps {
//                 echo 'Archiving the results...'
//                 script {
//                     docker.image('cpswt-core:latest').inside('-v $PWD:/app') {
//                         sh 'docker logs cpswt-core > cpswt-core.log'
//                     }
//                 }
//                 archiveArtifacts artifacts: 'cpswt-core.log', fingerprint: true
//             }
//         }
//         stage('Clean up') {
//             steps {
//                 echo 'Tearing Down the image & container....'
//                 sh 'docker rm -f cpswt-core'
//                 sh 'docker rmi cpswt-core:latest'
//             }
//         }
//     }

//     post {
//         always {
//             echo 'This will always run'
//             emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
//             recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
//             subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
//             attachLog: true,
//             attachmentsPattern: 'cpswt-core.log'
//         }
//     }   
// }
