// Do NOT place within the pipeline block 
properties([ [ $class: 'ThrottleJobProperty',
               categories: ['ci_cpswt_build'], 
               limitOneJobWithMatchingParams: false,
               maxConcurrentPerNode: 1,
               maxConcurrentTotal: 1,
               paramsToUseForLimit: '',
               throttleEnabled: true,
               throttleOption: 'category' ] ])

pipeline {
    agent any
    triggers {
        pollSCM('*/1 * * * *') // poll the SCM every 1 minutes
    }

    stages {
        stage('Clone repository') {
            steps {
                echo 'Cloning cpswt-omnetpp...'
                deleteDir() // Delete workspace before cloning
                sh 'git clone git@github.com:justinyeh1995/CI_with_Jenkins.git'
            }
        }
        stage('Build cpswt-omnetpp image') {
            steps {
                echo 'Start a Docker Container for this experiment, which should start the experiment and a archiva server, a inet server, and a omnet++ server..'
                // sh 'if docker images | grep -q cpswt-omnetpp:latest; then docker rmi cpswt-omnetpp:latest; fi' // Remove the existing image with the name:tag cpswt-omnetpp:latest
                dir("CI_with_Jenkins/cpswt-omnetpp") {
                    sh 'docker build -t cpswt-omnetpp:latest -f Dockerfile --build-arg ssh_prv_key="$(cat ~/.ssh/id_rsa)" --build-arg ssh_pub_key="$(cat ~/.ssh/id_rsa.pub)" .'
                }
            }
        }
        stage('Deploy image') {
            steps {
                echo 'Run the Docker Container inside Jenkins container'
                //sh 'if docker ps -a | grep -q cpswt-omnetpp; then docker stop cpswt-omnetpp; fi' //Stop the existing container with the name cpswt-omnetpp
                //sh 'if docker ps -a | grep -q cpswt-omnetpp; then docker rm -f cpswt-omnetpp; fi' // Remove the existing container with the name cpswt-omnetpp
                sh 'docker run \
                        --name cpswt-omnetpp \
                        --network host \
                        cpswt-omnetpp:latest'
            }
        }
        stage('Wait for cpswt-omnetpp container to stop') {
            options {
                timeout(time: 30, unit: 'MINUTES')
            }
            steps {
                echo 'Wait for container to stop'
                sh 'docker wait cpswt-omnetpp'
            }
        }
        stage('Archive loggings') {
            steps {
                echo 'Archiving cpswt-omnetpp results...'
                sh 'docker logs cpswt-omnetpp > cpswt-omnetpp.log'
                archiveArtifacts artifacts: 'cpswt-omnetpp.log', fingerprint: true
            }
        }
    }

    post {
        always {
            echo 'This will always run'
            emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                    recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                    subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                    attachLog: true,
                    attachmentsPattern: 'cpswt-omnetpp.log'
            // echo 'Tearing Down the image & container....'
            sh 'rm -rf cpswt-omnetpp'
            sh 'docker rm -f cpswt-omnetpp'
            sh 'docker rmi cpswt-omnetpp:latest'
        }
    }	
}
